### ISSUE TITLE
Sample usage

### ISSUE THREAD

**Issue by guestisp** [silviocamposs/cordova-plugin-sunmi-inner-printer#11]
Any sample usage with cordova ?

when calling, in example, sunmiInnerPriter.hasPrinter() it always returns undefined and so does any other method.

**Comment by eusilvio** [comment]
> Any sample usage with cordova ?
> 
> when calling, in example, sunmiInnerPriter.hasPrinter() it always returns undefined and so does any other method.
> 


1. Update plugin to version 1.1.0.
2. Use `navigator.sunmiInnerPrinter` to call methods. 

Example: 

`await navigator.sunmiInnerPrinter.hasPrinter()`
