### ISSUE TITLE
missing woyouService.cutPaper function

### ISSUE THREAD

**Issue by nileshgamit** [silviocamposs/cordova-plugin-sunmi-inner-printer#4]
Hi, this is very good plugin. I tried calling cutPaper function and it didn't work. I guess, sunmi has support for it but this plugin doesn't provide wrapper function for same. Any plan to provide support for same?

Thanks

**Comment by ahmad6242** [comment]
Can you Please give something to Cut the paper I am stuck here ? Please Help

**Comment by seeya** [comment]
Use the `sendRAWDATA` command.

```
sunmiInnerPrinter.sendRAWData("HVZCAA==");
```

**Comment by uokivan** [comment]
sunmi v1 can Cut paper or not ?

**Comment by nileshgamit** [comment]
@uokivan @ahmad6242 I can confirm that sunmi v1 prints and cut the paper after print with this plugin and code I've provided. You may try removing local cache for project before rebuilding your app.

Just for your information, I'm using meteor 1.7.0.5 with cordova 6.4.0 to build Android app.

Here is the entire code for your reference.
[sunmi-print-code.txt](https://github.com/silviocamposs/cordova-plugin-sunmi-inner-printer/files/2717920/sunmi-print-code.txt)

One point to note here is, 'sunmi is not printing text in order with non-native app'. I had couple of conversation with their support team and there was no resolution for this issue, so we ended up using Bixolon 302 printer.

**Comment by Ruslanko1** [comment]
> sunmi v1 can Cut paper or not ?


No, this device does not cut the paper automatically. Manually only

**Comment by eusilvio** [comment]
Hi, Sunmi V1 does not cut paper.
