### ISSUE TITLE
can use in SUNMI V2 PRO or not ??

### ISSUE THREAD

**Issue by uokivan** [silviocamposs/cordova-plugin-sunmi-inner-printer#5]
can use in SUNMI V2 PRO or not ??
Thanks a lot

**Comment by RaulNavas88** [comment]
Still waiting , someone?

**Comment by shahrinazuan87** [comment]
yes, it can if your sunmi sdk version is 1.1.0

**Comment by RichyFennell** [comment]
Hi guys,
Trying to use this with a Sunmi v2 pro but not having any luck. I am using it in capacitorJS, seems to be building correctly but not printing anything.

I the following have below my imports.

`let sunmiInnerPrinter:any;`

And then in my init:

```
    console.log('nginit');
    await sunmiInnerPrinter.printerInit();
    await sunmiInnerPrinter.printOriginalText('test');
    console.log('printed');
```

Been trying to get this working for over a week now so any help you can give would be amazing. I have tried with InnerPrinter util installed and not installed, no difference.

Thanks

Rich

**Comment by eusilvio** [comment]
Hello, I have not tested the plugin on Sunmi V2.
