### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by eapbox** [silviocamposs/cordova-plugin-sunmi-inner-printer#6]
BUILD FAILED in 2s
28 actionable tasks: 1 executed, 27 up-to-date
(node:16556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
C:\opt\work\SkyPOS\skyPOS\platforms\android\app\src\main\java\com\sunmi\innerprinter\Printer.java:12: error: package woyou.aidlservice.jiuiv5 does not exist
import woyou.aidlservice.jiuiv5.ICallback;

**Comment by tmalbonph** [comment]
@eapbox 
see how to build here `https://github.com/tmalbonph/cordova-plugin-sunmi-inner-printer`
