### ISSUE TITLE
Sunmi v2

### ISSUE THREAD

**Issue by RaulNavas88** [silviocamposs/cordova-plugin-sunmi-inner-printer#7]
Is working in sunmi v2 ?

Thanks in advance

**Comment by eusilvio** [comment]
I have not tested on v2 :(

**Comment by RaulNavas88** [comment]
So is working un v1?

**Comment by eusilvio** [comment]
Yes!

![WhatsApp Image 2019-07-18 at 11 01 11(1)](https://user-images.githubusercontent.com/17049089/61465883-53813d00-a94f-11e9-8547-07d20be4ba0b.jpeg)

**Comment by RaulNavas88** [comment]
How much will be cost setup in my app¿?

**Comment by eusilvio** [comment]
Email me and let's talk!

silviocampooss@gmail.com
