### ISSUE TITLE
Install , Setup the plugin

### ISSUE THREAD

**Issue by RaulNavas88** [silviocamposs/cordova-plugin-sunmi-inner-printer#8]
Someone who is able to install this plugin in my application, I have no problems paying for work and well? Email : navitasceuta@gmail.com whatsapp +34 667 52 97 50

**Comment by tmalbonph** [comment]
@Wariclis 
Already done this!

**Comment by oliverTS** [comment]
I need also help. added the plugin but cant use . any install help?
