### ISSUE TITLE
[ HOW TO BUILD ]

### ISSUE THREAD

**Issue by PabloGBarcelo** [silviocamposs/cordova-plugin-sunmi-inner-printer#9]
This only work with android@^6.3.0 (not 7.0.0 and 7.1.0)
Need to use build-tools: 28.0.3 (not 29.0.0)

With that configuration it build.

**Comment by tmalbonph** [comment]
@PabloGBarcelo 
You let `cordova` build it for you.
see `https://github.com/tmalbonph/cordova-plugin-sunmi-inner-printer`

**Comment by RaulNavas88** [comment]
> @PabloGBarcelo
> You let `cordova` build it for you.
> see `https://github.com/tmalbonph/cordova-plugin-sunmi-inner-printer`
@tmalbonph I m still waiting my integration , please i m texting you at whatsapp . Could you answer me?
